cluster.name: fraud-detection-cluster
node.name: fraud-node-1

# Network settings
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery settings
discovery.type: single-node

# Security settings
xpack.security.enabled: false
xpack.security.enrollment.enabled: false

# Memory settings
bootstrap.memory_lock: true

# Index settings
action.auto_create_index: true
action.destructive_requires_name: false

# Logging
logger.level: INFO