[server]
# Server configuration for production
maxUploadSize = 500
enableCORS = false
enableXsrfProtection = false

[browser]
# Browser configuration  
gatherUsageStats = false

[global]
# Global configuration
developmentMode = false

[theme]
# UI theme for better visibility
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
